base:
  project: winequality-project
  random_state: 42
  target_col: TARGET

data_source:
  s3_sources: data_given/winequality.csv

load_data:
  raw_dataset_csv: data/raw/winequality.csv
split_data:
  train_path: data/processed/train_winequality.csv
  test: 0.2

estimators:
  ElasticaNet:
    params:
    alpha: 0.88
    l1_ratio: 0.89

  model_dir: saved_models